#s = 'GATATATGCATATACTT'
#t = 'ATAT'
s = 'CACGCCTTACACGCCTAGCACGCCTACACGCCTCACGCCTGAAAGCCACGCCTCACGCCTTCACCACGCCTCACGCCTCACGCCTGGCACGCCTCGCTAAGGCACGCCTCACGCCTCTACACGCCTAGTGCACGCCTACACGCCTTCCACGCCTACACGCCTCGATCGTCCACGCCTCACGCCTCTGACAAAAAAACCTTCACGCCTCACGCCTCACGCCTGTGGCACGCCTCACGCCTCGTGCACGCCTCACGCCTCACGCCTGCCACGCCTCCCACGCCTCACGCCTGATTTACACGCCTTGAGGTGGCCCCCACGCCTGAGCACGCCTTGCCACGCCTTTTCACGCCTTCTCCACGCCTCCACGCCTGCACGCCTCACGCCTCACGCCTTTCACGCCTCACGCCTTCACGCCTAATCACGCCTCATTACACGCCTACACGCCTGCACGCCTCACGCCTCCCGGTTGCACGCCTCTCACGCCTTACACGCCTCCACGCCTACACGCCTGCGCACGCCTTCACGCCTGGACACGCCTGGCACGCCTATCACGCCTGGCACGCCTTGTGGGACTGCACGCCTAATATCACGCCTCCACGCCTCACGCCTCGCACGCCTTCGGCACACGCCTCTGTAACACGCCTCACGCCTTTGGCCACGCCTGCGGCTCACGCCTCACGCCTCTCAGCACGCCTCACGCCTGAACACGCCTTGCCGTCACGCCTAGATTTGCACGCCTCGGGACACGCCTACCGCCACACGCCTGGCCACGCCTCGTACACGCCTGGGCACGCCTAAACTAATTTCTCACGCCTATCACGCCTCCACGCCTCACGCCTCACGCCTTCACGCCTAA'
t = 'CACGCCTCA'

annot = []
for i in range(len(s)):
        if s[i] == t[0]:
                if i < (len(s)-len(t)+1):
                        annot.append(i)

result = []
for index in annot:
        if s[index:index+len(t)] == t:
                result.append(index+1)

for r in result: 
        print r,

