s = 'TTGAGGCGAGACTACCATGCAAGAAGCCTCTTTGCGCCTAACTTCATTGTGCAAAACCTCAAATAATACGATGTATATTAGTTAAAGGCAAGCCGAATTATGGCTACAATGGGTCTTGCCAGACCAGACACGACCGGCTGCCCAGATCCAACTCTTTAGCACACACGTGCATCCTCTTAAAGACGTAAGGCACGCCGTGGGTTGTTTCCCGTCTAGACGATCTTTGGGATGCGATAGCTAGGCAGCCCCTCATCTACGGATTTTTTTGATTGTATGACCTGCGGGTAAGACGAGATCGCGCCGTGAAAGACCTTCGACGTATACATAAGACTTAGATAGTCGCTAAGCTCTCGCTTATGTTCGGGAAGAAGACATGTCGAGCGTTCGGTTTTCGGATCGGCACGCGTAGCTAGCACCGTGCATTTTGTGATGGGCACCGTAGGGATAGAGAAAGGAGCGAAGTGCACATTAATTTAGGTAATAAGCATGGGAACTCCCGATAATCCTTCGATTTATGGGTATCATAGAACACTGCCGGTGAGCGGTAGCGAATTCGAGATAGAGCCTTGCGCAAAGCACAAACCAAACAGGTGCGTAAGGCGTGTATAGCCGTATTTCTTTTACAGTGGACGATCCATATGGTAGCGAGTAGGGAACCCCATCTTAACATACGGGTCTTGACCGAGCTCTTGCGAATAGCTACATAACCCGGTCGCAAAGTTTATGGGCTTAGATAGGAATTAGCTTATCTCGAACTATTCATCGGACGCCTTGTGAACTGCCGTTTGGCAGAAGGATTTGAATGGCTTTTATCCGCCATGGCGCGCTAAAAATCATACATCCTGTGCTCACCTACCGGATGGCTGGCTGCTTACAAGTTTGCATATGGCTGGCCCCCGTGGTCGACCCACAAAAATCTTGTCCACACGATGTGACTCGGTGAAGCTTTCAGGGCGGCTGTACGCGGTCCGTAAGTTCGTCACAAAACGAGGTATCTG'
c = {}
c['A'] = 0
c['C'] = 0
c['G'] = 0
c['T'] = 0
for i in range(len(s)):
        c[s[i:i+1]] = c[s[i:i+1]] + 1
print str(c['A']) + ' ' + str(c['C']) + ' ' + str(c['G']) + ' ' + str(c['T'])
